'Pass Statement ->It is used as a place holder when a statement is syntatically required. When it is used nothing hppens. Itis usually used in "if statement","loops","classes".'

def add():
    pass
def sub():
    pass
def mul():
    pass
def div():
    pass
if 5==5:
    pass
else:
    pass

student=['Romi','Saksham','Vinay','Toni']
for myStudent in student:
    pass

class students:
    pass

print('This is only the statement that got executed after passing all statements!!!!')