'Comparison of datatypes -> In python the data types are list, Tuple, String, Sets, Dictionary.'

'1> List :- It is a collection od data which is ordered and mutable and accepts duplicate members.'
myList=[2,2.25,'Romeo',True,2+3j,'Romeo']
print(myList)
print(type(myList))

'2> Tuple :- It is a collection of data which is ordered, immutable and accepts duplicate members.'
myTuple=(2,2.25,'Romeo',True,2+3j,'Romeo')
print(myTuple)
print(type(myTuple))

'3> Set :- It is a collection of data which is unordered and non-indexed, no duplicate members accepted,'
mySet={2,2.25,'Romeo',True,2+3j,'Romeo'}
print(mySet)
print(type(mySet))

'4> Dictionary :- Is is a collection of data which unordered, mutable and indexed but no duplicate members allowed. And data is in "key":"value" form'
myDictionary={"Firstname":"Romeo","Age":"30","Address":"Rohtak","Firstname":"Romeo"}
print(myDictionary)
print(type(myDictionary))
print(type(myDictionary))

'5> String :- It is data type which is immutable unicode code points'
myString='Romeo_Siwach'
print(myString)
print(type(myString))